import { createHash } from "node:crypto";
import { CompletionEngine } from "./completionEngine";
import { CompletionRequest, CompletionResult } from "./completionTypes";

export interface RequestSettings { debounceMs(): number; cacheEnabled(): boolean; cacheTtlMs(): number; cacheMaxEntries(): number; }
export interface CompletionStats { requested:number; backendRequests:number; cacheHits:number; negativeCacheHits:number; deduplicated:number; cancelled:number; succeeded:number; totalLatencyMs:number; }
type Active={id:number;key:string;controller:AbortController;promise:Promise<CompletionResult|null>}; type Entry={value:CompletionResult;expiresAt:number;documentKey:string;prefix:string;suffix:string;fingerprint:string};
export class RequestManager {
 private readonly active=new Map<string,Active>(); private readonly cache=new Map<string,Entry>(); private readonly negative=new Map<string,number>(); private id=0; private readonly stats:CompletionStats={requested:0,backendRequests:0,cacheHits:0,negativeCacheHits:0,deduplicated:0,cancelled:0,succeeded:0,totalLatencyMs:0};
 constructor(private readonly engine:CompletionEngine,private readonly settings:RequestSettings){}
 complete(documentKey:string,request:CompletionRequest,source:AbortSignal):Promise<CompletionResult|null>{this.stats.requested++;const key=this.key(request),cached=request.repositoryContextTask===undefined?(this.get(key)??this.refine(documentKey,request)):null;if(cached){this.stats.cacheHits++;return Promise.resolve(cached)}const negativeUntil=this.negative.get(key);if(request.repositoryContextTask===undefined&&negativeUntil!==undefined&&negativeUntil>Date.now()){this.stats.negativeCacheHits++;return Promise.resolve(null)}const current=this.active.get(documentKey);if(current?.key===key){this.stats.deduplicated++;return current.promise}current?.controller.abort();const controller=new AbortController(),id=++this.id;const abort=()=>controller.abort();source.addEventListener("abort",abort,{once:true});const promise=this.run(request,controller,id,documentKey,key).finally(()=>source.removeEventListener("abort",abort));this.active.set(documentKey,{id,key,controller,promise});return promise}
 private async run(request:CompletionRequest,c:AbortController,id:number,doc:string,key:string){const started=performance.now();try{await delay(this.debounce(request),c.signal);if(c.signal.aborted)return null;if(request.repositoryContextTask!==undefined){const repository=await settleWithin(request.repositoryContextTask,10,c.signal);if(!c.signal.aborted&&repository!==undefined)request.repositoryContext=repository;key=this.key(request);const cached=this.get(key);if(cached){this.stats.cacheHits++;return cached}}this.stats.backendRequests++;const result=await this.engine.complete(request,c.signal);if(c.signal.aborted||this.active.get(doc)?.id!==id)return null;if(result&&this.settings.cacheEnabled())this.set(key,result,doc,request);if(!result)this.negative.set(key,Date.now()+2000);if(result)this.stats.succeeded++;return result}catch{return null}finally{if(c.signal.aborted)this.stats.cancelled++;if(this.active.get(doc)?.id===id)this.active.delete(doc);this.stats.totalLatencyMs+=performance.now()-started}}
 clearCache(){this.cache.clear();this.negative.clear()} cancel(documentKey:string){this.active.get(documentKey)?.controller.abort()} cancelAll(){for(const a of this.active.values())a.controller.abort()} dispose(){this.cancelAll();this.active.clear();this.cache.clear();this.negative.clear()} getStats(){return {...this.stats}}
 private key(r:CompletionRequest){return createHash("sha256").update(r.language).update("\0").update(r.prefix.slice(-2000)).update("\0").update(r.suffix.slice(0,1000)).update("\0").update(r.repositoryContext?.fingerprint??"").digest("hex")}
 private get(k:string){const e=this.cache.get(k);if(!e||e.expiresAt<Date.now()){this.cache.delete(k);return null}this.cache.delete(k);this.cache.set(k,e);return e.value} private set(k:string,v:CompletionResult,documentKey:string,r:CompletionRequest){this.cache.delete(k);this.cache.set(k,{value:v,expiresAt:Date.now()+this.settings.cacheTtlMs(),documentKey,prefix:r.prefix,suffix:r.suffix,fingerprint:r.repositoryContext?.fingerprint??""});while(this.cache.size>this.settings.cacheMaxEntries())this.cache.delete(this.cache.keys().next().value!)}
 private refine(documentKey:string,r:CompletionRequest):CompletionResult|null{const fingerprint=r.repositoryContext?.fingerprint??"";for(const e of [...this.cache.values()].reverse()){if(e.expiresAt<Date.now()||e.documentKey!==documentKey||e.suffix!==r.suffix||e.fingerprint!==fingerprint||!r.prefix.startsWith(e.prefix))continue;const typed=r.prefix.slice(e.prefix.length);if(typed!==""&&e.value.text.startsWith(typed))return{text:e.value.text.slice(typed.length)}}return null}
 private debounce(r:CompletionRequest){const base=this.settings.debounceMs();return /[[.({=,:]$/.test(r.textBeforeCursorOnLine)?Math.min(base,70):base}
}
function delay(ms:number,s:AbortSignal){return new Promise<void>(resolve=>{const t=setTimeout(resolve,ms);s.addEventListener("abort",()=>{clearTimeout(t);resolve()},{once:true})})}
async function settleWithin<T>(promise:Promise<T>,ms:number,signal:AbortSignal):Promise<T|undefined>{return Promise.race([promise.catch(()=>undefined),delay(ms,signal).then(()=>undefined)])}
